language: php
php:
  - "hhvm"
  - "nightly"
  - "7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - composer install --dev
  - mysql -e 'create database stefano_tests;'
script: phpunit --configuration tests/phpunit.xml --coverage-clover tests/clover.xml
after_script:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml
matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly
        - php: "7"
