language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - composer install --dev
  - mysql -e 'create database stefano_tests;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('test') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script: phpunit --configuration tests/phpunit.xml --coverage-clover tests/clover.xml
after_script:
  - php vendor/bin/coveralls
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root